#:import MeshLinePlot kivy.garden.graph.MeshLinePlot

<TestingResultsInfoBox@Label>:
    font_size: 25
	color: 0,0,0,1
	halign: 'center'
	valign: 'center'
    canvas.before:
        Color:
            rgba: .74,.74,.74,1
        Rectangle:
            pos: self.pos
            size: self.size

<BarcodeDialog>:
    size_hint: (0.85, 0.55)
    markup: True
    bold: True
    title: 'Scan Barcode'
    title_align: 'center'
    title_size: '26sp'
    # size_hint: (0.5, 0.7)
    BoxLayout:
        orientation: 'vertical'
        Label:
            font_size: 26
            markup: True
            bold: True
            halign: 'center'
            text:"  select 'Cancel'"
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            size_hint_x: 1
            height: 65
            NavButton:
                text: "Skip"
                on_release: root.save_test()
            NavButton:
                text: "Done"
                on_release: root.save_test()

<TestingResultsScreen>:
	name: 'testing_results_screen'
    GranuContainer:
        GranuSideArea:
            GranuSideButton:
                text: 'Update\nNotes'
	    		on_release:
                    root.move_to('note_screen') # Move to note screen
            GranuSideButton:
                text: 'Break\nHeight'
	    		on_release:
                    root.move_to('break_height_screen') # Move to break height screen
            GranuSideButton:
                text: 'Reject'
	    		on_release:
                    root.move_to('testing_screen') # Move to main screen
            GranuSideButton:
                text: 'Save'
	    		on_release:
                    root.barcode_popup()
                    root.move_to('testing_screen') # Move to main screen
        GranuContent:
            GranuTitle:
                text: 'Testing Results'
                size_hint_max_y: 30
            GridLayout:
                cols: 2
                spacing: 10
                size_hint_y: 0.25
                GranuNoteButton:
                    text: "Break\nHeight"
                    on_release:
                        root.move_to('break_height_screen') # Move to note screen
                GranuNoteButton:
                    id: RootLodgeButton
                    on_release:
                        root.rootLodge_note()
            GridLayout:
                cols:2
                spacing: 10
                GridLayout:
                    rows: 2
                    GraphTitle:
                        text: 'Potentiometer Angle'
                    Graph:
                        id: graph_test1
                        plot: MeshLinePlot
                        background_color: 0, 0, 0, 1
                        xlabel:'Time(s)'
                        ylabel:'Angle (pot)'
                        x_ticks_major:root.x_major
                        y_ticks_major:root.y_major1
                        y_grid_label:True
                        x_grid_label:True
                        #padding:5
                        x_grid:True
                        y_grid:True
                        xmin:0
                        ymin:0
                        xmax:root.x_max
                        ymax:root.y_max1
                GridLayout:
                    rows: 2
                    GraphTitle:
                        text: 'X-Force Loading'
                    Graph:
                        id: graph_test2
                        plot: MeshLinePlot
                        background_color: 0, 0, 0, 1
                        xlabel:'Time(s)'
                        ylabel:'X Load (adc)'
                        x_ticks_major:root.x_major
                        y_ticks_major:root.y_major2
                        y_grid_label:True
                        x_grid_label:True
                        #padding:5
                        x_grid:True
                        y_grid:True
                        xmin:0
                        ymin:0
                        xmax:root.x_max
                        ymax:root.y_max2
